# Generated by Django 3.1.7 on 2021-04-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniqueID', models.CharField(max_length=10)),
                ('UserName', models.CharField(max_length=10)),
                ('FullName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Password', models.CharField(max_length=34)),
            ],
        ),
    ]
